const App = () => {
  return (
    <div>
      <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus ipsam reiciendis accusamus quod doloremque maiores quos repellendus illo, fugiat cum unde distinctio repellat fuga minus tempora nihil neque maxime fugit. Unde eligendi officiis itaque recusandae similique, accusamus at reprehenderit sed pariatur impedit odio excepturi nostrum quam quisquam quis sint inventore! Accusantium, nobis. Laborum reiciendis laudantium similique quibusdam exercitationem molestiae fugit neque debitis nihil. Libero eum neque voluptate ratione quam ipsa quasi voluptates deleniti? Eveniet nostrum repudiandae eligendi modi doloremque dicta? Alias autem voluptates totam doloribus dolor eum magnam eos iure, laboriosam libero? Aperiam quia earum error eveniet sequi quod officia eligendi commodi nesciunt, placeat soluta! Nostrum recusandae minus cum ex voluptatem, itaque blanditiis incidunt expedita sapiente aspernatur! Enim ab, debitis dolor, exercitationem minima autem sapiente ullam voluptate nemo blanditiis voluptatum fuga illum laboriosam rerum obcaecati impedit consequuntur quisquam natus. Quia libero expedita repellat culpa quae quod consectetur harum ex nesciunt iste totam dolore, accusamus exercitationem nisi assumenda id voluptas similique fugiat ipsam porro? Libero molestias, itaque perspiciatis praesentium distinctio, illum natus non soluta quaerat quos velit laboriosam unde necessitatibus aliquam ut assumenda, deserunt nostrum debitis modi eaque! Nulla modi pariatur, maiores veritatis, asperiores esse reprehenderit rerum, magni qui quis omnis sunt reiciendis? Natus beatae reprehenderit non impedit ad iste laboriosam corrupti quod ea, laudantium, aspernatur nisi in repellat. Ratione, incidunt! Obcaecati ea nobis molestias iure recusandae eius consectetur cumque repellat repudiandae esse distinctio, modi aliquid consequuntur. Beatae, quidem quis aspernatur deleniti ut sequi possimus asperiores totam nostrum aperiam! Iste quibusdam odio aperiam nemo, quidem vel. Porro nostrum aspernatur at quis cumque et assumenda sapiente quo? Alias quam fugiat sit est optio deserunt exercitationem nobis, deleniti, possimus quas labore quisquam itaque minus. Molestias fugiat eius aspernatur modi nesciunt obcaecati reiciendis eos minus? Corrupti at modi voluptas vitae inventore, magnam repellendus numquam?</h2>
    </div>
  );
};

export default App;
